# Generated by Django 4.2 on 2023-05-18 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiales', '0003_materiales_modelomaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=8)),
                ('ciudad', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('valorunitario', models.IntegerField()),
                ('valortotal', models.IntegerField()),
                ('descuento', models.IntegerField()),
                ('codigo', models.CharField(max_length=999999)),
                ('fecha', models.DateField()),
                ('descripcionservicio', models.CharField(max_length=100)),
                ('serviciototal', models.IntegerField()),
                ('preciodescuento', models.IntegerField()),
                ('cantidadutilizado', models.PositiveIntegerField()),
                ('materialutilizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.materiales')),
            ],
            options={
                'db_table': 'ordenTrabajo',
            },
        ),
    ]
