# Generated by Django 4.2 on 2023-04-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=80)),
                ('cantidad', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
            options={
                'db_table': 'material',
            },
        ),
    ]
