# Generated by Django 4.2 on 2023-04-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiales',
            name='material',
        ),
        migrations.AddField(
            model_name='materiales',
            name='costomaterial',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiales',
            name='nombrematerial',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiales',
            name='tipomedida',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
