# Generated by Django 4.2 on 2023-05-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_remove_materiales_material_materiales_costomaterial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales',
            name='modelomaterial',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
