# Generated by Django 4.2 on 2023-05-11 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_materiales_modelomaterial'),
        ('formulario', '0003_cliente_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='material',
            field=models.ForeignKey(default='ninguno', on_delete=django.db.models.deletion.CASCADE, to='materiales.materiales'),
        ),
    ]
