# Generated by Django 4.2 on 2023-04-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=8)),
                ('ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CostoEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('valorunitario', models.IntegerField()),
                ('valortotal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Opcionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripciono', models.CharField(max_length=100)),
                ('cantidado', models.IntegerField()),
                ('valorunitarioo', models.IntegerField()),
                ('valortotalo', models.IntegerField()),
                ('descuento', models.IntegerField()),
                ('valorTotalIva', models.IntegerField()),
            ],
        ),
    ]
